# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

os:
  - linux
  - osx

language: cpp

compiler:
  - gcc
  - clang

matrix:
  exclude:
    - os: osx
      compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

before_script:
  - cd ./build/unix
  - ./autogen.sh

script: "./configure && make"

